jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Load SSH private key into ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
    - continue-on-error: true
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      name: Run Ansible to Deploy
      run: 'pip install ansible==2.9.13

        cd infrastructure

        echo "$ANSIBLE_VAULT_PASSWORD" > vault_password

        ./run_ansible --environment production

        '
name: Deploy Production
on:
  repository_dispatch:
    types: trigger-ga___run-deploy-production.yml
