jobs:
  deploy:
    name: Run Bot Update Maps
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      name: Run Ansible to Deploy
      run: 'pip install ansible==2.9.13

        cd infrastructure

        echo "$ANSIBLE_VAULT_PASSWORD" > vault_password

        ./run_ansible --tags update_maps --environment production

        '
name: Run - Update Bot Maps
on:
  repository_dispatch:
    types: trigger-ga___run-bot-update-maps.yml
